### ISSUE TITLE
Use the aggregate values insead of the keys in the Evolution dashboard URL

### ISSUE THREAD

**Issue by o0Ignition0o** [mozilla/telemetry-dashboard#502] opened 2018-03-24 11:16 UTC
As of now, when we pick aggregates on the evolution dashboard, the URL keeps a list of selected keys, instead of values. 

As @chutten mentionned [here](https://github.com/mozilla/telemetry-dashboard/issues/395#issuecomment-368514169) This might be one cause of bug #395 and #404.
If not, this would still increase overall readability of the urls :)

Steps to reproduce : 
- Visit [this permalink](https://telemetry.mozilla.org/new-pipeline/evo.html)
- Click on eOK
- Select other aggregates :
![screenshot from 2018-03-24 12-08-16](https://user-images.githubusercontent.com/9465678/37863348-1a1fff6e-2f5d-11e8-90fa-5760959d61ba.png)

- Have a look at the url in the navigation bar : ` evo.html#!aggregates=0!2!3!4 ` 

The selected aggregate keys are separated by !.
It would be great if the values would be used instead, eg ` evo.html#!aggregates=eOk!eUnreachable!eChannelOpen ` etc.

**Comment by o0Ignition0o** [comment] 2018-03-24 11:33
The method used to generate the url is [saveStateToUrlAndCookie](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/new-pipeline/src/evo.js#L915) 

Maybe we could try to see what happens to ` $("#aggregates").val(); ` when an aggregate is [being updated](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/new-pipeline/src/evo.js#L385) ?

**Comment by o0Ignition0o** [comment] 2018-03-24 11:55
@Sylvia23 It seems like I'm not allowed to assign someone to an issue just yet, I'll ping @chutten and ask him to assign it to you :)

**Comment by Sylvia23** [comment] 2018-03-26 19:21
@o0Ignition0o @chutten , Actually I was looking into the code. Out of curiosity, I searched for options `eOK`, `eRequest`, `eUnreachable` and other `aggregate` drop-down options when the `measure` is set to `TELEMETRY_SEND_FAILURE_TYPE` running `git grep "eOK"` command.
What I found was that these words are present nowhere in the `telemetry-dashboard` repository but they are displayed in the frontend. 
So, are they showing up from backend or what? Can you please tell the probable reasons for this?
Thanks!

**Comment by o0Ignition0o** [comment] 2018-03-26 19:32
Hi @Sylvia23 
As you can see [here](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/v2/doc.md#examples) the data fetching seems to occur in Telemetry.js.
My guess is it happens somewhere around [here](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/v2/telemetry.js#L23).

You get to see the [BASE_URL](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/v2/telemetry.js#L12) where all the data is being fetched, as well as the parameters.
The great thing about it is that if we need to add an option somewhere, we might only have to add it on the server side, IE the place where BASE_URL points to, and the web page will be updated automatically :)

**Comment by Sylvia23** [comment] 2018-03-26 20:16
@o0Ignition0o , Thanks for the explanation. I have got some idea now that we can still render the `aggregate` names. I will now quickly give it a try playing with some functions like `updateAggregates` and `saveStateToUrlAndCookie()` and report back in a while. 
Thanks!

**Comment by chutten** [comment] 2018-05-29 15:55
Unassigning and reprioritizing due to inactivity.

**Comment by ab0092** [comment] 2018-08-09 20:08
@chutten could you assign this issue to me? I would like to work on this one.

**Comment by chutten** [comment] 2018-08-09 20:19
Sure. Let me know if you have any questions.

**Comment by ab0092** [comment] 2018-08-09 20:21
@chutten I cannot seem to reproduce the url which is mentioned in the above comments.

**Comment by chutten** [comment] 2018-08-09 20:26
I think a url exhibiting the original request would be https://mzl.la/2vSbvzG (which expands to https://telemetry.mozilla.org/new-pipeline/evo.html#!aggregates=bucket-0!bucket-3!bucket-4!bucket-7&cumulative=0&end_date=null&keys=&max_channel_version=nightly%252F63&measure=TELEMETRY_SEND_FAILURE_TYPE&min_channel_version=nightly%252F60&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=null&trim=1&use_submission_date=0)

See how the aggregates query parameter is "bucket-0!bucket-3!bucket-4!bucket-7"

**Comment by ab0092** [comment] 2018-08-09 20:32
Yes now i can see it. Setting the aggregate values instead of the keys wont be a problem i will just check once whether there will be any issues to re-populate the data back from the saved url.

**Comment by ab0092** [comment] 2018-08-11 19:36
@chutten i have implemented the required changes and you can view the changes at  https://ab0092.github.io/telemetry-dashboard/new-pipeline/evo.html . I have also submitted the PR so please review that as well and let men know if any further changes are required.

**Comment by chutten** [comment] 2018-08-27 19:11
This was fixed by #574

**Closed as completed by chutten** 2018-08-27 19:11 UTC
Labels: bug, measurement-dash, priority:3, assigned
