### ISSUE TITLE
Rename Aurora channel to DevEdition in the front-end

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#400] opened 2018-02-21 16:53 UTC
We still show aurora in multiple places.
My understanding is that this is the DevEdition data. Is that correct?

If yes, can we rename this in the UI to be "DevEdition" or similar, to make it clear to users?

**Comment by chutten** [comment] 2018-02-21 20:00
Is this a dupe of #398, @georgf ?

**Comment by georgf** [comment] 2018-02-22 12:00
Yes, somehow this was double-posted.
chutten said on #398:
> The channel names come from the aggregate service. I have filed [bug 1439919](https://bugzilla.mozilla.org/show_bug.cgi?id=1439919) to track discussion and work.

**Comment by georgf** [comment] 2018-02-26 17:00
The backend work in the filed bug might take a little.
In the mean-time, we can rename "aurora" to "dev edition" in the front-end, like the [dropdown here](https://screenshots.firefox.com/zEtLo4J097y0kJ6n/telemetry.mozilla.org).

This potentially affects evo.html, evo.js, dist.html, dist.js & dashboards.js in `/new-pipeline`.

**Comment by Sylvia23** [comment] 2018-02-27 21:04
@georgf , In this issue, what is the exact word/phrase that should be put in place of "aurora"?
Is it "dev edition" or "DevEdition" or something else?

**Comment by georgf** [comment] 2018-03-01 11:33
Sorry, i missed that. Given that the current names in that selection are all lower-case, i think "dev edition" should be good for now.

**Comment by Sylvia23** [comment] 2018-03-01 12:20
@georgf , Should I commit the changes or the issue has been solved? I have changed the name to "dev edition". I was working on it. Thanks!

**Comment by Sylvia23** [comment] 2018-03-01 12:46
@georgf , The results can not be seen in the frontend. This maybe due to some backend issues that you were talking about.
Please have a look. Thanks!

**Comment by georgf** [comment] 2018-03-01 17:33
Hi @Sylvia23, i don't see any changes to this [in the front-end](https://bit.ly/2ozVVpx). Or am i misunderstanding you?
The next step is for us to review your PR in #425.

**Comment by Sylvia23** [comment] 2018-03-01 17:51
@georgf , Does backend control the display of name "aurora" in the UI ? Sometimes it happens that backend control the display. I misunderstood that you were saying backend has some bugs due to which we can't the change the name in the UI. 
If It is not the case, then I will look into the codebase again to fix this issue and report ASAP.
Also, I am unable to open the link "in the front-end" in your comment.
`Error : Connection times out`
Thanks!

**Comment by georgf** [comment] 2018-03-01 17:56
I commented over on #425, but to clear this up:
- the backend currently returns data that contains "aurora", "aurora/59", etc.
- in the front-end, we can map this to something nicer, to show to the user, that's what `getHumanReadableOptions()` does.
- so, in the front-end we want to rename "aurora" to "dev edition" to be more user-friendly.

**Comment by kdrosado** [comment] 2018-03-15 06:23
@georgf, Is this issue resolved and no longer open?

**Comment by Sylvia23** [comment] 2018-03-15 06:38
Hi, I am working on it. Thanks!

**Closed as completed** 2018-03-19 15:45 UTC
Labels: measurement-dash, mentored, priority:3, assigned
