### ISSUE TITLE
First Click on the aggregates selector on Evolution dashboard sometimes does not select anything

### ISSUE THREAD

**Issue by o0Ignition0o** [mozilla/telemetry-dashboard#404] opened 2018-02-26 07:18 UTC
This might be related to #395

STR:
    visit [this permalink](https://telemetry.mozilla.org/new-pipeline/evo.html#!aggregates=0&cumulative=0&end_date=2018-01-08&keys=!__none__!__none__&max_channel_version=beta%252F58&measure=TELEMETRY_SEND_FAILURE_TYPE&min_channel_version=beta%252F53&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2017-11-15&trim=1&use_submission_date=0)
    click on "eOK"
    try to tick "abort"
    Observe (your first click is discarded).
    You can now ckeck the boxes as expected.

This issue was commented [in this comment](https://github.com/mozilla/telemetry-dashboard/issues/395#issuecomment-368305759)

**Comment by Sylvia23** [comment] 2018-02-26 12:20
Hi there, I'm interested in working on this issue.
I also tried to tick the checkbox, but it got discarded on the first click. 
I would like to start fixing this.

**Comment by o0Ignition0o** [comment] 2018-02-26 14:03
Hi and welcome, 
Thank's a lot for taking the time to have a look at this.
If you run into any trouble or have any question, please let me know :)

**Comment by Sylvia23** [comment] 2018-02-26 15:31
Hi @o0Ignition0o ,
Has there been a decision on what exactly is to be implemented for it? Any advice on where and how to get started with the implementation is also most welcome!

**Comment by o0Ignition0o** [comment] 2018-02-26 16:01
I think that [right here](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/new-pipeline/src/evo.js#L262) is the code that is run when the aggregates get changed.

What I would first do is [set a breakpoint](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Set_a_breakpoint) on this file and click on the link, to see what happens.

Do you see anything weird? 
Is there anything wrong during the first click event, being right during the subsequent ones ?

It might be related to the way the state is being restored on #395 (An incorrect state restore could lead to wrong options being displayed).

I'm sorry I'm horrible at explaining things, so if you have any questions please let me know :)

**Comment by Sylvia23** [comment] 2018-02-26 23:46
@o0Ignition0o , Thanks for the explanation. 
I am thinking of the steps which can be used to identify the cause and fix the bug.
I will let you know if I am stuck somewhere.
Thanks!

**Comment by Sylvia23** [comment] 2018-03-17 19:52
@o0Ignition0o , I missed this because I was occupied with some other issues. Now, I have started working on it. I saw the code for `aggregates` in `evo.js` file. 
Can you please give some more pointers to this. I have tried debugging using breakpoints but it doesn't seem to work as of now. 
Thanks!

**Comment by o0Ignition0o** [comment] 2018-03-21 19:42
Hey there :) sorry I've been away.
I'll have an other look at it tomorrow and give you some pointers if I find them :)

**Comment by Sylvia23** [comment] 2018-03-22 19:36
@o0Ignition0o , Yeah ! Thank you.

**Comment by o0Ignition0o** [comment] 2018-03-24 11:06
Ok so it took me quite a while, but I think we have a battle plan to tackle this tricky, yet very interresting bug :) 

The fist step would be to [Use the aggregates values instead of keys when the url is updated](https://github.com/mozilla/telemetry-dashboard/issues/502). This will allow us to see the exact aggregate values we ticked in the url.

The second step would be to use the url aggregates values to restore the state of the Evolution dashboard.

If the bug still occurs, we will go back to the code that is being run when the aggregates are changed, and figure out what is going on :)

We might even fix #395 in the process ! :) 

This bug seems a bit tricky, but I'm pretty confident we can handle it together if we break it down into simple separate tasks :)

I'll file separate issues for the first and the second step, so it will be easier to track and handle it step by step :)

Would you like to work on it ? If so let's try to complete the first step together, and see how we can progress from there !

**Comment by Sylvia23** [comment] 2018-03-24 11:49
@o0Ignition0o , Yeah I would be happy to work on it. Could you please assign it to me. Thanks.

**Comment by o0Ignition0o** [comment] 2018-03-24 11:53
Sure, cheers !

**Comment by o0Ignition0o** [comment] 2018-03-24 11:59
By the way as we were investigating #502 together, it seems like we found out what happens in this bug !

We only need to change one character to map on the value insead of the key [here](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/new-pipeline/src/evo.js#L409).

Can you guess how to fix it ? A breakpoint on this line, or a console.log on newAggregates might be useful :)

**Comment by Sylvia23** [comment] 2018-03-26 21:09
@o0Ignition0o , I figured it out while solving #502. Please see #504 . Thanks!

**Comment by chutten** [comment] 2018-05-29 15:56
Unassigning and reprioritizing due to inactivity.

**Closed as completed** 2018-06-05 20:50 UTC
Labels: bug, measurement-dash, mentored, priority:2
