### ISSUE TITLE
Keyed histogram shown as unkeyed

### ISSUE THREAD

**Issue by vdjeric** [mozilla/telemetry-dashboard#183] opened 2015-10-01 19:51 UTC
STR:
1. Open Histogram dashboard
2. Select histogram PLUGIN_ACTIVATION_COUNT

Expected: shown as a keyed histogram
Actual: shown as a regular count histogram! Generated URL: https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2015-09-30&keys=flash!__none__!__none__!__none__&max_channel_version=nightly%252F44&measure=PLUGIN_ACTIVATION_COUNT&min_channel_version=null&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2015-09-29&table=0&trim=1&use_submission_date=0

However, if I disable data sanitization, then I get the correct graph:

https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=1&e10s=true&end_date=2015-09-30&keys=flash!npvlc!nplwaplugin!npbecon&max_channel_version=nightly%252F44&measure=PLUGIN_ACTIVATION_COUNT&min_channel_version=null&os=Windows_NT&product=Firefox&sanitize=0&sort_keys=median&start_date=2015-09-27&table=0&trim=1&use_submission_date=0

**Comment by vdjeric** [comment] 2015-10-01 19:56
Basically there's not enough submissions for keys other than "Flash" and when "data sanitization" is enabled in the dash (which it is by default), the dash ignores the other keys and only shows the 1 key with enough submissions, making it look like an unkeyed histogram

**Comment by chutten** [comment] 2015-11-24 17:45
@vdjeric that first link shows as a keyed histogram for me. Maybe the data for the other plugins have filled in since?

**Comment by vdjeric** [comment] 2015-11-25 22:29
@chutten Yes, that's likely what happened, but the bug likely remains. Keyed histograms should never be presented in the format of unkeyed histograms

**Comment by chutten** [comment] 2017-06-20 15:44
This is a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1365751

Please follow along there if you'd like.

**Closed by chutten** 2017-06-20 15:44 UTC
