### ISSUE TITLE
Probe dictionary gives confusing count of probes

### ISSUE THREAD

**Issue by jryans** [mozilla/telemetry-dashboard#536] opened 2018-04-19 18:49 UTC
If you [search for "trigger"](https://telemetry.mozilla.org/probe-dictionary/?search=trigger&searchtype=in_name) in the dictionary, you see confusing output:

![image](https://user-images.githubusercontent.com/279572/39011826-32ad7ed2-43d8-11e8-975f-6645e851d151.png)

It says "Found 3 probes" but only 1 row appears.

It seems this is tied to filters somehow. If I change "channel any" to "channel nightly":

![image](https://user-images.githubusercontent.com/279572/39011878-5763431a-43d8-11e8-8199-283f1dbf7736.png)

...all 3 appear.

Maybe the UI should be more explicit that there were text matches, but they are hidden by channel filters?

**Comment by chutten** [comment] 2018-04-19 19:05
Huh, "any" should explicitly _include_ nightly. There should be no change in the display between the two screenshots. Both should have those three.

This will likely prove to be an interesting bug.

**Comment by abhinandan1995** [comment] 2018-07-03 21:01
So i was looking into this issue. @chutten And i can't seem to repro it. Is it still an issue?

**Comment by chutten** [comment] 2018-07-03 21:04
I'm not sure. It has been a little while since it was filed, so this is entirely possible.

Some possible next steps would be:

1) Ask the person who reported it for help reproducing it
2) Look around merged pull requests here and in mozilla/probe-dictionary to see if there's anything obvious that may have fixed it in the interim
3) Find a new thing to work on while you wait for 1) to happen : )

**Comment by jryans** [comment] 2018-07-03 21:18
This issue still exists, but you can't reproduce anymore with the original steps. The issue only exists for probes that have only been seen for some but not all channels, which changes over time. For example, when a new probe is first added, it is only recorded by the nightly channel at first, but eventually makes its way to all channels.

As an example that works right now, [search for "DOCGROUPS"](https://telemetry.mozilla.org/probe-dictionary/?search=DOCGROUPS&searchtype=in_name). Channel any says "found 4 probes" but only lists 2.

**Comment by georgf** [comment] 2018-07-04 15:48
@jryans I have a fix up over at #560, does that look good to you?
[Here is a live instance](https://georgf.github.io/telemetry-dashboard/probe-dictionary/?search=docgroup) of the fixed probe dictionary.

**Comment by jryans** [comment] 2018-07-05 19:55
@georgf Thanks, that does seem to fix this issue! 😁 

While testing your fixed instance, I noticed the following:

* Changing from channel any to nightly causes the "recorded" column for probes like ACTIVE_HTTP_DOCGROUPS_PER_TABGROUP to change from "62 to 62" to "63 to 63"; I would expect channel any to say "62 to 63" (the superset of info from different channels), but I might not fully understand the value being shown here

Seems like a separate issue or possibly working as designed.

**Closed as completed** 2018-07-06 12:09 UTC
Labels: bug, priority:2, probe-dictionary

**Comment by georgf** [comment] 2018-07-06 12:40
> Changing from channel any to nightly causes the "recorded" column for probes like ACTIVE_HTTP_DOCGROUPS_PER_TABGROUP to change from "62 to 62" to "63 to 63"; I would expect channel any to say "62 to 63" (the superset of info from different channels), but I might not fully understand the value being shown here

Hm, i see your point and have a hard time seeing which option is better.

Currently this is "as designed" and i was hoping it makes intuitive sense for users.
The idea is that if you look at probes from a specific channel, you'd want to know the state on that channel.

We could change it to show the super set, but i wonder if that is confusing in other ways.

**Comment by georgf** [comment] 2018-07-06 12:40
But yes, happy to dive into that more in a separate issue 👍
